repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.43.0
  hooks:
    - id: terraform_tflint
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-merge-conflict
    - id: pretty-format-json
      files: '.*\.json$'
      args:
        - --autofix
        - --indent=2
