repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_tflint
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: detect-aws-credentials
      args:
        - --allow-missing-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: pretty-format-json
      files: '.*\.json$'
      args:
        - --autofix
        - --indent=2
    - id: trailing-whitespace
